export const APP_ERROR_CODES = {
  CONFIG_FILE_NOT_FOUND: "CONFIG_FILE_NOT_FOUND",
  CONFIG_FILE_INVALID: "CONFIG_FILE_INVALID",
  CONFIG_INVALID_VALUE: "CONFIG_INVALID_VALUE",
  COMMAND_NOT_SUPPORTED: "COMMAND_NOT_SUPPORTED",
  SEARCH_QUERY_REQUIRED: "SEARCH_QUERY_REQUIRED",
  CONTEXT_TARGET_REQUIRED: "CONTEXT_TARGET_REQUIRED",
  PARSER_ROUTE_UNSUPPORTED: "PARSER_ROUTE_UNSUPPORTED",
  PARSER_ADAPTER_UNAVAILABLE: "PARSER_ADAPTER_UNAVAILABLE",
  PARSER_COMPLEX_SKIPPED: "PARSER_COMPLEX_SKIPPED",
  PARSER_COMPLEX_FORMAT_UNSUPPORTED: "PARSER_COMPLEX_FORMAT_UNSUPPORTED",
  PARSER_COMPLEX_CONTENT_UNREADABLE: "PARSER_COMPLEX_CONTENT_UNREADABLE",
  PARSER_COMPLEX_LIBRARY_FAILED: "PARSER_COMPLEX_LIBRARY_FAILED",
  PARSER_COMPLEX_OUTPUT_INVALID: "PARSER_COMPLEX_OUTPUT_INVALID",
  PARSER_UNKNOWN_ERROR: "PARSER_UNKNOWN_ERROR",
  SQLITE_QUERY_FAILED: "SQLITE_QUERY_FAILED",
  WATCH_PATH_NOT_FOUND: "WATCH_PATH_NOT_FOUND",
  SEARCH_INDEX_INVALID: "SEARCH_INDEX_INVALID",
  EXPORT_INVALID_PAYLOAD: "EXPORT_INVALID_PAYLOAD",
  MCP_INVALID_REQUEST: "MCP_INVALID_REQUEST",
  INTERNAL_UNKNOWN_ERROR: "INTERNAL_UNKNOWN_ERROR",
} as const;

export type AppErrorCode = typeof APP_ERROR_CODES[keyof typeof APP_ERROR_CODES];
